# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='q'),
            preserve_default=False,
        ),
    ]
